# Detailed Transformation Scenarios (15–20)

## 1. Exceedance flags vs daily/hourly standards

In [241]:
import pandas as pd
import numpy as np

In [242]:
df=pd.read_csv('cleaned_dataset.csv', encoding='latin1')

In [243]:
df['PM2_5_flag_daily']=df['PM2_5']>df['Pollutant_standard_daily']
df['PM2_5_flag_hourly']=df['PM2_5']>df['Pollutant_standard_hourly']

In [244]:
df['PM2_5_flag_daily'].head(5)

0    True
1    True
2    True
3    True
4    True
Name: PM2_5_flag_daily, dtype: bool

In [245]:
df['PM2_5_flag_daily'].unique()

array([ True, False])

In [246]:
ans={True:1,False:0}
df['PM2_5_flag_daily']=df['PM2_5_flag_daily'].map(ans)

In [247]:
df['PM2_5_flag_daily'].unique()

array([1, 0], dtype=int64)

In [248]:
df['PM2_5_flag_daily']

0        1
1        1
2        1
3        1
4        1
        ..
14574    1
14575    1
14576    1
14577    1
14578    1
Name: PM2_5_flag_daily, Length: 14579, dtype: int64

In [249]:
df['PM2_5_flag_hourly']=df['PM2_5_flag_hourly'].map(ans)

In [250]:
df['SO2_flag_daily']=df['SO2']>df['Pollutant_standard_daily']
df['SO2_flag_hourly']=df['SO2']>df['Pollutant_standard_hourly']


In [251]:
df['SO2_flag_daily'].head(5)

0     True
1     True
2    False
3     True
4     True
Name: SO2_flag_daily, dtype: bool

In [252]:
df['SO2_flag_daily'].unique()

array([ True, False])

In [253]:
df['SO2_flag_daily']=df['SO2_flag_daily'].map(ans)

In [254]:
df['SO2_flag_daily'].unique()

array([1, 0], dtype=int64)

In [255]:
df['SO2_flag_daily']

0        1
1        1
2        0
3        1
4        1
        ..
14574    1
14575    0
14576    1
14577    0
14578    1
Name: SO2_flag_daily, Length: 14579, dtype: int64

In [256]:
df['SO2_flag_hourly']=df['SO2_flag_hourly'].map(ans)

In [257]:
df['NOx_flag_daily']=df['NOx']>df['Pollutant_standard_daily']
df['NOx_flag_hourly']=df['NOx']>df['Pollutant_standard_hourly']


In [258]:
df['NOx_flag_daily'].head(5)

0    False
1     True
2    False
3     True
4     True
Name: NOx_flag_daily, dtype: bool

In [259]:
df['NOx_flag_daily'].unique()

array([False,  True])

In [260]:
df['NOx_flag_daily']=df['NOx_flag_daily'].map(ans)

In [261]:
df['NOx_flag_daily'].unique()

array([0, 1], dtype=int64)

In [262]:
df['NOx_flag_daily']

0        0
1        1
2        0
3        1
4        1
        ..
14574    0
14575    1
14576    1
14577    1
14578    1
Name: NOx_flag_daily, Length: 14579, dtype: int64

In [263]:
df['NOx_flag_hourly']=df['NOx_flag_hourly'].map(ans)

In [264]:
df.loc[0:10,['PM2_5','SO2','NOx','Pollutant_standard_daily','PM2_5_flag_daily','SO2_flag_daily','NOx_flag_daily','Pollutant_standard_hourly','PM2_5_flag_hourly','SO2_flag_hourly','NOx_flag_hourly']]

,PM2_5,SO2,NOx,Pollutant_standard_daily,PM2_5_flag_daily,SO2_flag_daily,NOx_flag_daily,Pollutant_standard_hourly,PM2_5_flag_hourly,SO2_flag_hourly,NOx_flag_hourly
0,157.84,50.28,26.06,35.6,1,1,0,91.3,1,0,0
1,83870.00,29840.00,35490.00,56.9,1,1,1,66.5,1,1,1
2,155.72,18.32,50.14,64.9,1,0,0,145.8,1,0,0
3,153280.00,62150.00,28010.00,40.3,1,1,1,107.4,1,1,1
4,71150.00,11060.00,122410.00,46.3,1,1,1,176.4,1,1,1
5,279.26,20.39,112.83,28.8,1,0,1,76.7,1,0,1
6,59.58,30.52,69.09,80.8,0,0,0,57.3,1,0,1
7,152.31,15.26,82.44,99.8,1,0,0,55.0,1,0,1
8,115640.00,13250.00,38920.00,67.4,1,1,1,133.7,1,1,1
9,117070.00,44240.00,35770.00,91.0,1,1,1,67.5,1,1,1


## 2. Pollutant AQI sub‑index computation and overall AQI

In [265]:
PM2_5_limit=60

SO2_limit=80

NOx_limit=80

In [266]:
df['PM2_5_SubIndex']=(df['PM2_5']/60) * 100
df['SO2_SubIndex']=(df['SO2']/80) * 100
df['NOx_SubIndex']=(df['NOx']/80) * 100

In [267]:
df['Overall_AQI']=df[
    ['PM2_5_SubIndex','SO2_SubIndex','NOx_SubIndex']
].max(axis=1)

In [268]:
df.loc[0:11,['PM2_5','SO2','NOx','PM2_5_SubIndex','SO2_SubIndex','NOx_SubIndex','Overall_AQI']]

,PM2_5,SO2,NOx,PM2_5_SubIndex,SO2_SubIndex,NOx_SubIndex,Overall_AQI
0,157.84,50.28,26.06,263.066667,62.8500,32.5750,263.066667
1,83870.00,29840.00,35490.00,139783.333333,37300.0000,44362.5000,139783.333333
2,155.72,18.32,50.14,259.533333,22.9000,62.6750,259.533333
3,153280.00,62150.00,28010.00,255466.666667,77687.5000,35012.5000,255466.666667
4,71150.00,11060.00,122410.00,118583.333333,13825.0000,153012.5000,153012.500000
5,279.26,20.39,112.83,465.433333,25.4875,141.0375,465.433333
6,59.58,30.52,69.09,99.300000,38.1500,86.3625,99.300000
7,152.31,15.26,82.44,253.850000,19.0750,103.0500,253.850000
8,115640.00,13250.00,38920.00,192733.333333,16562.5000,48650.0000,192733.333333
9,117070.00,44240.00,35770.00,195116.666667,55300.0000,44712.5000,195116.666667


## 3. Emission load (kg/day) from concentration and flow

In [269]:
df["Flow_Rate"] = 1500

df["PM2_5_Emission_Load"] = (df["PM2_5"] * df["Flow_Rate"] * 24) / 1000
df["SO2_Emission_Load"] = (df["SO2"] * df["Flow_Rate"] * 24) / 1000
df["NOx_Emission_Load"] = (df["NOx"] * df["Flow_Rate"] * 24) / 1000

In [270]:
print(df[["PM2_5", "Flow_Rate", "PM2_5_Emission_Load"]].head())

       PM2_5  Flow_Rate  PM2_5_Emission_Load
0     157.84       1500              5682.24
1   83870.00       1500           3019320.00
2     155.72       1500              5605.92
3  153280.00       1500           5518080.00
4   71150.00       1500           2561400.00


In [271]:
print(df[["SO2", "Flow_Rate", "SO2_Emission_Load"]].head())

        SO2  Flow_Rate  SO2_Emission_Load
0     50.28       1500            1810.08
1  29840.00       1500         1074240.00
2     18.32       1500             659.52
3  62150.00       1500         2237400.00
4  11060.00       1500          398160.00


In [272]:
print(df[["NOx", "Flow_Rate", "NOx_Emission_Load"]].head())

         NOx  Flow_Rate  NOx_Emission_Load
0      26.06       1500             938.16
1   35490.00       1500         1277640.00
2      50.14       1500            1805.04
3   28010.00       1500         1008360.00
4  122410.00       1500         4406760.00


## 4. Rolling 24‑hour averages and percentiles

In [273]:
df["TS"] = pd.to_datetime(df["TS"])
df = df.sort_values(["Plant_ID", "TS"]).reset_index(drop=True)

In [274]:
df["PM2_5_Rolling_Avg"] = (df.groupby("Plant_ID")["PM2_5"].rolling(window=24).mean().reset_index(level=0, drop=True)) 
df["PM2_5_Rolling_Avg"] = df["PM2_5_Rolling_Avg"].fillna(df["PM2_5"])

df["SO2_Rolling_Avg"] = (df.groupby("Plant_ID")["SO2"].rolling(window=24).mean().reset_index(level=0, drop=True))
df["SO2_Rolling_Avg"] = df["SO2_Rolling_Avg"].fillna(df["SO2"])

df["NOx_Rolling_Avg"] = (df.groupby("Plant_ID")["NOx"].rolling(window=24).mean().reset_index(level=0, drop=True))
df["NOx_Rolling_Avg"] = df["NOx_Rolling_Avg"].fillna(df["NOx"])

In [275]:
df["PM2_5_25th_Percentile"] = df["PM2_5"].quantile(0.25)
df["PM2_5_50th_Percentile"] = df["PM2_5"].quantile(0.50)
df["PM2_5_75th_Percentile"] = df["PM2_5"].quantile(0.75)

df["SO2_25th_Percentile"] = df["SO2"].quantile(0.25)
df["SO2_50th_Percentile"] = df["SO2"].quantile(0.50)  
df["SO2_75th_Percentile"] = df["SO2"].quantile(0.75)

df["NOx_25th_Percentile"] = df["NOx"].quantile(0.25)
df["NOx_50th_Percentile"] = df["NOx"].quantile(0.50)
df["NOx_75th_Percentile"] = df["NOx"].quantile(0.75)

In [276]:
df["PM2_5_75th_Percentile"].head(40)

0     89920.0
1     89920.0
2     89920.0
3     89920.0
4     89920.0
5     89920.0
6     89920.0
7     89920.0
8     89920.0
9     89920.0
10    89920.0
11    89920.0
12    89920.0
13    89920.0
14    89920.0
15    89920.0
16    89920.0
17    89920.0
18    89920.0
19    89920.0
20    89920.0
21    89920.0
22    89920.0
23    89920.0
24    89920.0
25    89920.0
26    89920.0
27    89920.0
28    89920.0
29    89920.0
30    89920.0
31    89920.0
32    89920.0
33    89920.0
34    89920.0
35    89920.0
36    89920.0
37    89920.0
38    89920.0
39    89920.0
Name: PM2_5_75th_Percentile, dtype: float64

In [277]:
print(df[["Plant_ID","TS","PM2_5","PM2_5_Rolling_Avg","PM2_5_25th_Percentile","PM2_5_50th_Percentile","PM2_5_75th_Percentile"]].head(30))

   Plant_ID                  TS      PM2_5  PM2_5_Rolling_Avg  \
0     PL-01 2026-03-01 06:18:00     157.84         157.840000   
1     PL-01 2026-03-01 11:59:00   83870.00       83870.000000   
2     PL-01 2026-03-01 15:30:00     155.72         155.720000   
3     PL-01 2026-03-01 15:35:00  153280.00      153280.000000   
4     PL-01 2026-03-01 15:54:00   71150.00       71150.000000   
5     PL-01 2026-03-01 16:25:00     279.26         279.260000   
6     PL-01 2026-03-01 18:20:00      59.58          59.580000   
7     PL-01 2026-03-01 19:08:00     152.31         152.310000   
8     PL-01 2026-03-01 20:13:00  115640.00      115640.000000   
9     PL-01 2026-03-01 21:42:00  117070.00      117070.000000   
10    PL-01 2026-03-01 22:19:00  125570.00      125570.000000   
11    PL-01 2026-03-02 00:38:00   77160.00       77160.000000   
12    PL-01 2026-03-02 00:39:00      28.50          28.500000   
13    PL-01 2026-03-02 01:00:00      37.91          37.910000   
14    PL-01 2026-03-02 01

In [278]:
print(df[["Plant_ID","TS","SO2","SO2_Rolling_Avg","SO2_25th_Percentile","SO2_50th_Percentile","SO2_75th_Percentile"]].head(30))

   Plant_ID                  TS       SO2  SO2_Rolling_Avg  \
0     PL-01 2026-03-01 06:18:00     50.28        50.280000   
1     PL-01 2026-03-01 11:59:00  29840.00     29840.000000   
2     PL-01 2026-03-01 15:30:00     18.32        18.320000   
3     PL-01 2026-03-01 15:35:00  62150.00     62150.000000   
4     PL-01 2026-03-01 15:54:00  11060.00     11060.000000   
5     PL-01 2026-03-01 16:25:00     20.39        20.390000   
6     PL-01 2026-03-01 18:20:00     30.52        30.520000   
7     PL-01 2026-03-01 19:08:00     15.26        15.260000   
8     PL-01 2026-03-01 20:13:00  13250.00     13250.000000   
9     PL-01 2026-03-01 21:42:00  44240.00     44240.000000   
10    PL-01 2026-03-01 22:19:00  29540.00     29540.000000   
11    PL-01 2026-03-02 00:38:00  68040.00     68040.000000   
12    PL-01 2026-03-02 00:39:00     37.31        37.310000   
13    PL-01 2026-03-02 01:00:00     19.24        19.240000   
14    PL-01 2026-03-02 01:22:00     20.45        20.450000   
15    PL

In [279]:
print(df[["Plant_ID","TS","NOx","NOx_Rolling_Avg","NOx_25th_Percentile","NOx_50th_Percentile","NOx_75th_Percentile"]].head(30))

   Plant_ID                  TS        NOx  NOx_Rolling_Avg  \
0     PL-01 2026-03-01 06:18:00      26.06        26.060000   
1     PL-01 2026-03-01 11:59:00   35490.00     35490.000000   
2     PL-01 2026-03-01 15:30:00      50.14        50.140000   
3     PL-01 2026-03-01 15:35:00   28010.00     28010.000000   
4     PL-01 2026-03-01 15:54:00  122410.00    122410.000000   
5     PL-01 2026-03-01 16:25:00     112.83       112.830000   
6     PL-01 2026-03-01 18:20:00      69.09        69.090000   
7     PL-01 2026-03-01 19:08:00      82.44        82.440000   
8     PL-01 2026-03-01 20:13:00   38920.00     38920.000000   
9     PL-01 2026-03-01 21:42:00   35770.00     35770.000000   
10    PL-01 2026-03-01 22:19:00   98540.00     98540.000000   
11    PL-01 2026-03-02 00:38:00   54790.00     54790.000000   
12    PL-01 2026-03-02 00:39:00      45.66        45.660000   
13    PL-01 2026-03-02 01:00:00      69.05        69.050000   
14    PL-01 2026-03-02 01:22:00      50.05        50.05